PORTNAME=	dockerbox
PORTVERSION=	0.1.0
CATEGORIES=	linux

MAINTAINER=	leafoliages@gmail.com
COMMENT=	Docker daemon inside virtualized Linux
WWW=		https://github.com/leafoliage/freebsd-dockerbox

ONLY_FOR_ARCHS=	amd64

RUN_DEPENDS=	grub2-bhyve>0:sysutils/grub2-bhyve

USES=	metaport

USE_GITHUB=	yes
GH_ACCOUNT=	leafoliage
GH_PROJECT=	freebsd-dockerbox

.include <bsd.port.mk>
